<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar  navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <!-- Navbar content -->

        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{'search'}}">Search Expense</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{'income'}}">Total Income</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{'expense'}}">Total Expense</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{'expense'}}">Last 5 Expense</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{'expense'}}">Last 5 Income</a>
                  </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown link
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>

      </nav>

    <h1 class="text-center mt-5">Expense Tracker HomePAge</h1>
    <button type="button" class="btn btn-primary"
        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
        <a class="text-dark" href="{{'search'}}">Expense Search Page</a>

</button>
<button type="button" class="btn btn-primary"
        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
        <a class="text-dark" href="{{'income'}}">Overall Income Page</a>

</button>


     <div class="container">
        <table class="table table-striped" id="dataTable">
           <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Type</th>
                <th>Amount</th>
                <th>Date</th>
            </tr>
           </thead>
           <tbody>
                <!-- Table body will be filled dynamically -->
            </tbody>

        </table>
     </div>
     <div id="pagination">
        <!-- Pagination links will be inserted here -->
        <ul class="pagination">
            <!-- Your pagination links generated by Laravel will be inserted here -->
        </ul>
    </div>

    <script>
         $(document).ready(function() {
        fetch_data();

        function fetch_data(page = 1) {
            $.ajax({
                url: '/',
                method: 'GET',
                dataType: 'json',
                data: {page: page}, // Send page number in AJAX request
                success: function(response) {
                    // Clear existing table body
                    $('#dataTable tbody').empty();
                    $.each(response.data, function(index, item) {
                        $('#dataTable tbody').append('<tr><td>' + item.Title + '</td><td>' + item.Description + '</td><td>' + item.Type + '</td><td>' +  item.Amount  +'</td><td>'+ item.Date +'</td></tr>');
                        // Add more cells as needed for additional data
                    });

                    // Update pagination links
                    $('#pagination').html(response.links);
                },
                error: function(xhr, status, error) {
                    // If there's an error during the AJAX request, handle it here
                    console.error(xhr.responseText); // Log the error message
                }
            });
        }

        $(document).on('click', '#pagination a', function(event) {
            event.preventDefault();
            var page = $(this).attr('href').split('page=')[1];
            fetch_data(page);
        });
    });
    </script>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>
